name: example
description: Example of Google Sign-In plugin.

dependencies:
  flutter:
    sdk: flutter
  google_sign_in:
    path: ../../google_sign_in/
  google_sign_in_web:
    path: ../
  http: ^0.12.0

flutter:
  uses-material-design: true
